In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
# 1) Load auto-mpg-clean data

car_data = pd.read_csv('dataset/auto-mpg-clean.csv') #read the data

## display the top 5 data

car_data.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
1,26.0,4,97.0,46,1950,21.0,73,2,volkswagen super beetle
2,43.1,4,90.0,48,1985,21.5,78,2,volkswagen rabbit custom diesel
3,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
4,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)

In [5]:
# 1) Load auto-mpg-clean data

car_data = pd.read_csv('dataset/auto-mpg-clean.csv') #read the data

## display the top 5 data

car_data.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
1,26.0,4,97.0,46,1950,21.0,73,2,volkswagen super beetle
2,43.1,4,90.0,48,1985,21.5,78,2,volkswagen rabbit custom diesel
3,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
4,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)

In [7]:
# 2) Extract weight as X (feature) and fuel consumption (mpg) as Y (label)
# 3) Create LinearRegression model from Scikit Learn package and fit the data
# You may add additional variables within the brackets or reshape the data


'''
X = car_data.iloc[:,4:5]
Y = car_data.iloc[:,0:1]

# or

X = car_data['weight'].to_numpy()
Y = car_data['mpg'].to_numpy()

X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)
'''
# or

X = car_data[['weight']]
Y = car_data['mpg']

In [9]:
lin_reg = LinearRegression()

lin_reg.fit(X,Y)

LinearRegression()

In [11]:
lin_reg = LinearRegression()

lin_reg.fit(X,Y)

LinearRegression()

In [13]:
Y_pred = lin_reg.predict(X)

r2_value = r2_score(Y, Y_pred)


print("Coefficients: ", lin_reg.coef_)
print("Intercept: ", lin_reg.intercept_)

# The coefficient of determination: 1 is perfect prediction

print('R-squared Coefficient of determination: %.2f' %r2_value)

Coefficients:  [-0.00764734]
Intercept:  46.21652454901758
R-squared Coefficient of determination: 0.69

In [15]:
# 6) Append the predicted data
car_data['Y_pred'] = Y_pred
print(car_data.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  26.0          4          97.0          46    1835          20.5
1  26.0          4          97.0          46    1950          21.0
2  43.1          4          90.0          48    1985          21.5
3  44.3          4          90.0          48    2085          21.7
4  43.4          4          90.0          48    2335          23.7

   model year  origin                         car name     Y_pred
0          70       2     volkswagen 1131 deluxe sedan  32.183651
1          73       2          volkswagen super beetle  31.304207
2          78       2  volkswagen rabbit custom diesel  31.036550
3          80       2             vw rabbit c (diesel)  30.271815
4          80       2               vw dasher (diesel)  28.359980

In [31]:
# 1) Load Input dataset

my_data = pd.read_csv('dataset/Income3.csv')

#print the first 5 data

my_data.head(5)

# 2) Extract data

X = my_data['Years of Higher Education (x)'].to_numpy()
Y = my_data['Income (y)'].to_numpy()

X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)

# 3) The create Linear Regression class and fit the data.

lin_reg = LinearRegression()

lin_reg.fit(X,Y)

# 4) Predict income data (Y) based on number of years in higher education (X)

Y_pred = lin_reg.predict(X)


# 5) Display Coefficient, Intercept 

print("Coefficients: ", lin_reg.coef_)
print("Intercept: ", lin_reg.intercept_)


# 6) R-square using r2_score function from Scikit Learn metrics package

r2_data = r2_score(Y, Y_pred)
print('R-squared Coefficient of determination: %.2f' %r2_value)


# 7) Predict a single data eg. print the output expected income for 3 years in higher education

yeasofeducation = 3

predicted_income = lin_reg.predict([[yeasofeducation]])


print("Predicted income with 3 years higher education is :%.2f" %predicted_income)

Coefficients:  [[7692.92437864]]
Intercept:  [37264.82601798]
R-squared Coefficient of determination: 0.69
Predicted income with 3 years higher education is :60343.60

C:\Users\darre\AppData\Local\Temp\ipykernel_23592\3479568768.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("Predicted income with 3 years higher education is :%.2f" %predicted_income)

In [33]:
car_data = pd.read_csv('dataset/auto-mpg-clean.csv',header=0, skipinitialspace=True) #read the data

In [35]:
# Prepare input and target label data
# Set the matrixes
# For 2 variables for multiple regression. You may add additional variables within the brackets

#split
#X = car_data.to_numpy()
#X = X[:, 1:]

#or
#select the column

X = car_data[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']] 
Y = car_data['mpg']

#make sure the dimension is correct
print (X.shape)
print (Y.shape)

(392, 6)
(392,)

In [41]:
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

print('Intercept: \n', lin_reg.intercept_)
print('Coefficients: \n', lin_reg.coef_)

Intercept:
 -14.535250480506154
Coefficients:
 [-3.29859089e-01  7.67843024e-03 -3.91355574e-04 -6.79461791e-03
  8.52732469e-02  7.53367180e-01]

In [43]:
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

print('Intercept: \n', lin_reg.intercept_)
print('Coefficients: \n', lin_reg.coef_)

Intercept:
 -14.535250480506154
Coefficients:
 [-3.29859089e-01  7.67843024e-03 -3.91355574e-04 -6.79461791e-03
  8.52732469e-02  7.53367180e-01]

In [84]:
# Create two dimensional array called new_data with proposed data

new_data = [[4, 97, 48, 2000, 23.8, 80]]

# Predict mpg and display
p_mpg = lin_reg.predict(new_data)


print('Predicted mpg info is %.2f' %p_mpg)

Predicted mpg info is 33.58

C:\Users\darre\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\darre\AppData\Local\Temp\ipykernel_23592\3798751788.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('Predicted mpg info is %.2f' %p_mpg)